import js from "@eslint/js";
import tseslint from "typescript-eslint";
import soarwx from "./tools/eslint-plugin-soarwx/index.js";

/** Directories whose exported functions must cite their sources (NF-6). */
const PHYSICS_GLOBS = [
  "src/thermo/**/*.ts",
  "src/convection/**/*.ts",
  "src/clouds/**/*.ts",
  "src/stability/**/*.ts",
  "src/orographic/**/*.ts",
];

export default tseslint.config(
  // `test/docs/examples/` is generated by `tools/checkApiExamples.ts` from code blocks
  // in `docs/API.md`. They are not linted: what matters is that they
  // **compile**, which is checked by `pnpm typecheck`.
  {
    ignores: [
      "dist/**",
      "coverage/**",
      "node_modules/**",
      ".claude/**",
      ".gstack/**",
      "test/docs/examples/**",
      // Standalone script for documentation generator: not included in package
      // tsconfig, so excluded from typed linter as well.
      "tools/api-docs/*.mjs",
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.strictTypeChecked,
  ...tseslint.configs.stylisticTypeChecked,

  {
    languageOptions: {
      parserOptions: { projectService: true, tsconfigRootDir: import.meta.dirname },
    },
    plugins: { soarwx },
    rules: {
      "@typescript-eslint/consistent-type-imports": "error",
      "@typescript-eslint/explicit-module-boundary-types": "error",
      "@typescript-eslint/no-non-null-assertion": "error",
      "no-restricted-syntax": [
        "error",
        {
          selector: "TSAsExpression > TSAnyKeyword",
          message: "`as any` is forbidden.",
        },
      ],
    },
  },

  // The library must run in the browser and in Node without a custom build
  // (NF-3): no Node-only APIs in `src/`.
  {
    files: ["src/**/*.ts"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              group: ["node:*", "fs", "path", "url", "crypto"],
              message: "`src/` must run in the browser: no Node APIs allowed (NF-3).",
            },
          ],
        },
      ],
    },
  },

  // The core does not access the network. Only `src/openmeteo/` may.
  {
    files: ["src/**/*.ts"],
    ignores: ["src/openmeteo/**/*.ts"],
    rules: {
      "no-restricted-globals": [
        "error",
        {
          name: "fetch",
          message: "Only `src/openmeteo/` accesses the network (SPEC §13).",
        },
        {
          name: "XMLHttpRequest",
          message: "Only `src/openmeteo/` accesses the network.",
        },
      ],
    },
  },

  // NF-6: mandatory source citation in physics modules.
  {
    files: PHYSICS_GLOBS,
    rules: { "soarwx/require-source-citation": "error" },
  },

  // NF-5: unit suffix on every numeric property of an exported type.
  {
    files: ["src/**/*.ts"],
    rules: { "soarwx/unit-suffix": "error" },
  },

  // Only exception: types describing the Open-Meteo response as it arrives.
  // Those property names belong to the API, and renaming them would break
  // JSON parity. Conversion to internal units and branded types happens in
  // `normalize.ts`, which enforces the rule.
  {
    files: ["src/openmeteo/types.ts"],
    rules: { "soarwx/unit-suffix": "off" },
  },

  // The lint plugin and its test suite are JavaScript: disable type-checking.
  {
    files: ["**/*.js"],
    ...tseslint.configs.disableTypeChecked,
    rules: {
      ...tseslint.configs.disableTypeChecked.rules,
      "@typescript-eslint/explicit-module-boundary-types": "off",
    },
  },

  // In tests, `!` after an assertion is idiomatic and safe: the precondition
  // is already verified with `expect`.
  {
    files: ["test/**/*.ts", "tools/**/*.js"],
    rules: {
      "@typescript-eslint/no-unsafe-assignment": "off",
      "@typescript-eslint/no-non-null-assertion": "off",
    },
  },
);
