/* GENERATED by tools/checkApiExamples.ts from docs/API.md.
   Do not edit by hand: regenerate with `pnpm docs:examples`.

   If a library signature changes and the example fails to compile,
   `pnpm typecheck` will fail, ensuring documentation is fixed
   before release. */

import type * as Root from "../../../src/index.js";
import type * as Snd from "../../../src/sounding/index.js";
import type * as Cnv from "../../../src/convection/index.js";
import type * as Rep from "../../../src/report/index.js";
import type * as Fct from "../../../src/forecast/index.js";
import type * as Uni from "../../../src/units/index.js";
import type * as Om from "../../../src/openmeteo/index.js";

declare const site: Root.Site;
declare const fuentemilanos: Root.Site;
declare const sounding: Snd.Sounding;
declare const surface: Snd.SurfaceState;
declare const pressureLevels: readonly Snd.RawPressureLevel[];
declare const heightLevels: readonly Snd.RawHeightLevel[];
declare const samples: readonly Cnv.FluxSample[];
declare const hourly: readonly Rep.HourlyObservation[];
declare const hours: readonly Fct.ScoredHour[];
declare const day: Rep.SoaringDay;
declare const maxSurfaceTempK: Uni.Kelvin;
declare const wStarMs: Uni.MPerS;
declare const ziAglM: Uni.Metres;
declare const fixture: Om.OpenMeteoResponse;
declare const container: { innerHTML: string };

import * as en from "../../../src/i18n/en.js";

/** `soarwx/i18n/en` */
export async function example(): Promise<unknown> {
  en.describeLevel(4);                       // "Good"
  en.describeCeilingLimit("hcrit");          // "limited by thermal strength"
  en.describeVeto("stable_atmosphere");      // "Stable atmosphere above a shallow convective layer"
  en.describeThermalQuality("organised");    // "Well-organised thermals"
  en.describeConfidence("medium");           // "Medium confidence"
  
  en.formatHour("2026-08-19T14:00", site.timezone);      // "16:00"
  en.formatInstant("2026-08-19T14:00", site.timezone);   // "19 August at 16:00"
  
  en.DISCLAIMER;   // "Advisory forecast only. This does not replace..."
  void [en];
  return undefined;
}
