/* GENERATED by tools/checkApiExamples.ts from docs/API.md.
   Do not edit by hand: regenerate with `pnpm docs:examples`.

   If a library signature changes and the example fails to compile,
   `pnpm typecheck` will fail, ensuring documentation is fixed
   before release. */

import type * as Root from "../../../src/index.js";
import type * as Snd from "../../../src/sounding/index.js";
import type * as Cnv from "../../../src/convection/index.js";
import type * as Rep from "../../../src/report/index.js";
import type * as Fct from "../../../src/forecast/index.js";
import type * as Uni from "../../../src/units/index.js";
import type * as Om from "../../../src/openmeteo/index.js";

declare const site: Root.Site;
declare const fuentemilanos: Root.Site;
declare const sounding: Snd.Sounding;
declare const surface: Snd.SurfaceState;
declare const pressureLevels: readonly Snd.RawPressureLevel[];
declare const heightLevels: readonly Snd.RawHeightLevel[];
declare const samples: readonly Cnv.FluxSample[];
declare const hourly: readonly Rep.HourlyObservation[];
declare const hours: readonly Fct.ScoredHour[];
declare const day: Rep.SoaringDay;
declare const maxSurfaceTempK: Uni.Kelvin;
declare const wStarMs: Uni.MPerS;
declare const ziAglM: Uni.Metres;
declare const fixture: Om.OpenMeteoResponse;
declare const container: { innerHTML: string };

import { buildSounding, interpolateAtAgl, findInversions, meanWind, maxGapBelow } from "../../../src/sounding/index.js";
import { m } from "../../../src/units/index.js";

/** `soarwx/sounding` */
export async function example(): Promise<unknown> {
  const built = buildSounding({ site, timeUtc: "2026-08-19T14:00", surface, pressureLevels, heightLevels });
  if (!built.ok) throw new Error(built.error.code);
  const sounding = built.value;
  
  sounding.quality.levelsDiscardedBelowGround;  // how many fell below the terrain
  sounding.quality.maxVerticalGapM;             // the largest remaining gap
  
  // Temperature at 1500 m above the field, interpolating linearly in log-p:
  const level = interpolateAtAgl(sounding, m(1500));
  if (level.ok) level.value.tempK;
  
  // Inversions and stable layers in the first 5 km, with 100 m minimum thickness:
  for (const layer of findInversions(sounding)) {
    layer.kind;          // "inversion" | "isothermal" | "stable"
    layer.baseMslM;
    layer.strengthK;
  }
  
  // Mixed-layer mean wind, averaging U/V components rather than degrees:
  const mean = meanWind(
    sounding.levels
      .filter((l) => l.geopotentialMslM < 3000)
      .map((l) => ({ wind: { speedMs: l.windSpeedMs, fromDeg: l.windFromDeg }, weight: 1 })),
  );
  mean.speedMs;
  mean.fromDeg;
  void [buildSounding, interpolateAtAgl, findInversions, meanWind, maxGapBelow, m, built, sounding, level, mean];
  return undefined;
}
