/* GENERATED by tools/checkApiExamples.ts from docs/API.md.
   Do not edit by hand: regenerate with `pnpm docs:examples`.

   If a library signature changes and the example fails to compile,
   `pnpm typecheck` will fail, ensuring documentation is fixed
   before release. */

import type * as Root from "../../../src/index.js";
import type * as Snd from "../../../src/sounding/index.js";
import type * as Cnv from "../../../src/convection/index.js";
import type * as Rep from "../../../src/report/index.js";
import type * as Fct from "../../../src/forecast/index.js";
import type * as Uni from "../../../src/units/index.js";
import type * as Om from "../../../src/openmeteo/index.js";

declare const site: Root.Site;
declare const fuentemilanos: Root.Site;
declare const sounding: Snd.Sounding;
declare const surface: Snd.SurfaceState;
declare const pressureLevels: readonly Snd.RawPressureLevel[];
declare const heightLevels: readonly Snd.RawHeightLevel[];
declare const samples: readonly Cnv.FluxSample[];
declare const hourly: readonly Rep.HourlyObservation[];
declare const hours: readonly Fct.ScoredHour[];
declare const day: Rep.SoaringDay;
declare const maxSurfaceTempK: Uni.Kelvin;
declare const wStarMs: Uni.MPerS;
declare const ziAglM: Uni.Metres;
declare const fixture: Om.OpenMeteoResponse;
declare const container: { innerHTML: string };

import { computeDay } from "../../../src/report/index.js";
import { renderSkewT } from "../../../src/render/index.js";
import { m } from "../../../src/units/index.js";

/** The long path */
export async function example(): Promise<unknown> {
  const day = computeDay({
    site: fuentemilanos,
    hourly,                       // HourlyObservation[], already in SI
    dateLocal: "2026-08-19",
    sunriseUtc: "2026-08-19T05:31",
    sunsetUtc: "2026-08-19T19:09",
  });
  
  if (day.ok && day.value.best !== null) {
    const svg = renderSkewT(day.value.best.sounding, {
      parcelFromK: day.value.best.sounding.surface.tempK,
      ceilingMslM: m(fuentemilanos.elevationMslM + day.value.best.ceiling.aglM),
    });
    container.innerHTML = svg;
  }
  void [computeDay, renderSkewT, m, day];
  return undefined;
}
