/* GENERATED by tools/checkApiExamples.ts from docs/API.md.
   Do not edit by hand: regenerate with `pnpm docs:examples`.

   If a library signature changes and the example fails to compile,
   `pnpm typecheck` will fail, ensuring documentation is fixed
   before release. */

import type * as Root from "../../../src/index.js";
import type * as Snd from "../../../src/sounding/index.js";
import type * as Cnv from "../../../src/convection/index.js";
import type * as Rep from "../../../src/report/index.js";
import type * as Fct from "../../../src/forecast/index.js";
import type * as Uni from "../../../src/units/index.js";
import type * as Om from "../../../src/openmeteo/index.js";

declare const site: Root.Site;
declare const fuentemilanos: Root.Site;
declare const sounding: Snd.Sounding;
declare const surface: Snd.SurfaceState;
declare const pressureLevels: readonly Snd.RawPressureLevel[];
declare const heightLevels: readonly Snd.RawHeightLevel[];
declare const samples: readonly Cnv.FluxSample[];
declare const hourly: readonly Rep.HourlyObservation[];
declare const hours: readonly Fct.ScoredHour[];
declare const day: Rep.SoaringDay;
declare const maxSurfaceTempK: Uni.Kelvin;
declare const wStarMs: Uni.MPerS;
declare const ziAglM: Uni.Metres;
declare const fixture: Om.OpenMeteoResponse;
declare const container: { innerHTML: string };

import { isErr } from "../../../src/index.js";
import { criticalHeight } from "../../../src/convection/index.js";
import { GLIDER_CLUB } from "../../../src/aircraft/index.js";

/** Errors */
export async function example(): Promise<unknown> {
  const climb = criticalHeight(wStarMs, ziAglM, GLIDER_CLUB);
  if (isErr(climb)) {
    if (climb.error.code === "NO_CONVECTION") return "it's night";  // valid state
    throw new Error(climb.error.code);
  }
  void [isErr, criticalHeight, GLIDER_CLUB, climb];
  return undefined;
}
