/* GENERATED by tools/checkApiExamples.ts from docs/API.md.
   Do not edit by hand: regenerate with `pnpm docs:examples`.

   If a library signature changes and the example fails to compile,
   `pnpm typecheck` will fail, ensuring documentation is fixed
   before release. */

import type * as Root from "../../../src/index.js";
import type * as Snd from "../../../src/sounding/index.js";
import type * as Cnv from "../../../src/convection/index.js";
import type * as Rep from "../../../src/report/index.js";
import type * as Fct from "../../../src/forecast/index.js";
import type * as Uni from "../../../src/units/index.js";
import type * as Om from "../../../src/openmeteo/index.js";

declare const site: Root.Site;
declare const fuentemilanos: Root.Site;
declare const sounding: Snd.Sounding;
declare const surface: Snd.SurfaceState;
declare const pressureLevels: readonly Snd.RawPressureLevel[];
declare const heightLevels: readonly Snd.RawHeightLevel[];
declare const samples: readonly Cnv.FluxSample[];
declare const hourly: readonly Rep.HourlyObservation[];
declare const hours: readonly Fct.ScoredHour[];
declare const day: Rep.SoaringDay;
declare const maxSurfaceTempK: Uni.Kelvin;
declare const wStarMs: Uni.MPerS;
declare const ziAglM: Uni.Metres;
declare const fixture: Om.OpenMeteoResponse;
declare const container: { innerHTML: string };

import { fetchSoaringDay } from "../../../src/openmeteo/index.js";
import { GLIDER_CLUB } from "../../../src/aircraft/index.js";
import * as en from "../../../src/i18n/en.js";
import { m } from "../../../src/units/index.js";
import type { Site } from "../../../src/index.js";

/** The short path */
export async function example(): Promise<unknown> {
  const fuentemilanos: Site = {
    name: "Fuentemilanos",
    icao: "LEFM",
    latDeg: 40.9167,
    lonDeg: -4.2333,
    elevationMslM: m(1013),
    timezone: "Europe/Madrid",
    surface: { type: "cropland" },
  };
  
  const result = await fetchSoaringDay(fuentemilanos, "2026-08-19", {
    models: ["icon_eu", "gfs_seamless"],
    profile: GLIDER_CLUB,
  });
  
  if (!result.ok) throw new Error(result.error.code);
  
  const { day } = result.value;
  const best = day.best;
  if (best !== null) {
    console.log(`${en.describeLevel(best.score.level)} at ${en.formatHour(best.timeUtc, fuentemilanos.timezone)}`);
    console.log(`ceiling ${Math.round(best.ceiling.aglM)} m AGL, ${en.describeCeilingLimit(best.ceiling.limitedBy)}`);
    for (const veto of best.score.vetoes) console.log("⚠", en.describeVeto(veto.id));
  }
  console.log(day.attribution);   // must be displayed: CC BY 4.0
  void [fetchSoaringDay, GLIDER_CLUB, en, m, fuentemilanos, result, best, day];
  return undefined;
}
