/* GENERATED by tools/checkApiExamples.ts from docs/API.md.
   Do not edit by hand: regenerate with `pnpm docs:examples`.

   If a library signature changes and the example fails to compile,
   `pnpm typecheck` will fail, ensuring documentation is fixed
   before release. */

import type * as Root from "../../../src/index.js";
import type * as Snd from "../../../src/sounding/index.js";
import type * as Cnv from "../../../src/convection/index.js";
import type * as Rep from "../../../src/report/index.js";
import type * as Fct from "../../../src/forecast/index.js";
import type * as Uni from "../../../src/units/index.js";
import type * as Om from "../../../src/openmeteo/index.js";

declare const site: Root.Site;
declare const fuentemilanos: Root.Site;
declare const sounding: Snd.Sounding;
declare const surface: Snd.SurfaceState;
declare const pressureLevels: readonly Snd.RawPressureLevel[];
declare const heightLevels: readonly Snd.RawHeightLevel[];
declare const samples: readonly Cnv.FluxSample[];
declare const hourly: readonly Rep.HourlyObservation[];
declare const hours: readonly Fct.ScoredHour[];
declare const day: Rep.SoaringDay;
declare const maxSurfaceTempK: Uni.Kelvin;
declare const wStarMs: Uni.MPerS;
declare const ziAglM: Uni.Metres;
declare const fixture: Om.OpenMeteoResponse;
declare const container: { innerHTML: string };

import { GLIDER_CLUB, ASH_25, RASP_REFERENCE, AIRCRAFT_PROFILES, findAircraftProfile } from "../../../src/aircraft/index.js";
import { criticalHeight, expectedVarioAt } from "../../../src/convection/index.js";

/** `soarwx/aircraft` */
export async function example(): Promise<unknown> {
  // The ceiling does not depend on the glider: the 225 fpm criterion fixes it.
  criticalHeight(wStarMs, ziAglM, GLIDER_CLUB);       // 2364 m AGL
  criticalHeight(wStarMs, ziAglM, ASH_25);            // the same 2364 m AGL
  
  // What does depend on the glider is what the vario shows.
  expectedVarioAt(wStarMs, ziAglM, ziAglM, ASH_25);   // more than with GLIDER_CLUB
  
  // With RASP's reference, the vario drops to zero right at hcrit.
  RASP_REFERENCE.circlingSinkMs === RASP_REFERENCE.hcritThresholdMs;
  
  findAircraftProfile("duo-discus");                  // one from the catalogue
  AIRCRAFT_PROFILES.length;                           // 12
  void [GLIDER_CLUB, ASH_25, RASP_REFERENCE, AIRCRAFT_PROFILES, findAircraftProfile, criticalHeight, expectedVarioAt];
  return undefined;
}
