/* GENERATED by tools/checkApiExamples.ts from docs/API.md.
   Do not edit by hand: regenerate with `pnpm docs:examples`.

   If a library signature changes and the example fails to compile,
   `pnpm typecheck` will fail, ensuring documentation is fixed
   before release. */

import type * as Root from "../../../src/index.js";
import type * as Snd from "../../../src/sounding/index.js";
import type * as Cnv from "../../../src/convection/index.js";
import type * as Rep from "../../../src/report/index.js";
import type * as Fct from "../../../src/forecast/index.js";
import type * as Uni from "../../../src/units/index.js";
import type * as Om from "../../../src/openmeteo/index.js";

declare const site: Root.Site;
declare const fuentemilanos: Root.Site;
declare const sounding: Snd.Sounding;
declare const surface: Snd.SurfaceState;
declare const pressureLevels: readonly Snd.RawPressureLevel[];
declare const heightLevels: readonly Snd.RawHeightLevel[];
declare const samples: readonly Cnv.FluxSample[];
declare const hourly: readonly Rep.HourlyObservation[];
declare const hours: readonly Fct.ScoredHour[];
declare const day: Rep.SoaringDay;
declare const maxSurfaceTempK: Uni.Kelvin;
declare const wStarMs: Uni.MPerS;
declare const ziAglM: Uni.Metres;
declare const fixture: Om.OpenMeteoResponse;
declare const container: { innerHTML: string };

import { lcl, saturationVapourPressure, potentialTemperature, moistAdiabaticLift } from "../../../src/thermo/index.js";
import { K, Pa, celsiusToK, hPaToPa } from "../../../src/units/index.js";

/** `soarwx/thermo` */
export async function example(): Promise<unknown> {
  saturationVapourPressure(K(273.15));       // 611.2 Pa — the textbook value
  
  const t = celsiusToK(34.6);
  const td = celsiusToK(6.8);
  const p = hPaToPa(909);
  
  const base = lcl(t, td, p);
  base.heightAboveParcelM;                   // 3461 m above the starting point
  base.pressurePa;                           // 60660 Pa
  
  // The Espy rule the predecessor used gave 3392 m for the same case:
  // (34.6 - 6.8) * 122. At spreads of 28 °C the approximation breaks down.
  
  potentialTemperature(t, p);                // 316.3 K — nearly 9 K above T
  void [lcl, saturationVapourPressure, potentialTemperature, moistAdiabaticLift, K, Pa, celsiusToK, hPaToPa, t, td, p, base];
  return undefined;
}
