/* GENERATED by tools/checkApiExamples.ts from docs/API.md.
   Do not edit by hand: regenerate with `pnpm docs:examples`.

   If a library signature changes and the example fails to compile,
   `pnpm typecheck` will fail, ensuring documentation is fixed
   before release. */

import type * as Root from "../../../src/index.js";
import type * as Snd from "../../../src/sounding/index.js";
import type * as Cnv from "../../../src/convection/index.js";
import type * as Rep from "../../../src/report/index.js";
import type * as Fct from "../../../src/forecast/index.js";
import type * as Uni from "../../../src/units/index.js";
import type * as Om from "../../../src/openmeteo/index.js";

declare const site: Root.Site;
declare const fuentemilanos: Root.Site;
declare const sounding: Snd.Sounding;
declare const surface: Snd.SurfaceState;
declare const pressureLevels: readonly Snd.RawPressureLevel[];
declare const heightLevels: readonly Snd.RawHeightLevel[];
declare const samples: readonly Cnv.FluxSample[];
declare const hourly: readonly Rep.HourlyObservation[];
declare const hours: readonly Fct.ScoredHour[];
declare const day: Rep.SoaringDay;
declare const maxSurfaceTempK: Uni.Kelvin;
declare const wStarMs: Uni.MPerS;
declare const ziAglM: Uni.Metres;
declare const fixture: Om.OpenMeteoResponse;
declare const container: { innerHTML: string };

import { fetchSoaringDay, memoryCache, MODEL_CAPABILITIES, soundingModels } from "../../../src/openmeteo/index.js";
import { GLIDER_CLUB } from "../../../src/aircraft/index.js";

/** `soarwx/openmeteo` */
export async function example(): Promise<unknown> {
  // Multiple models + spread-based confidence, in one call:
  const result = await fetchSoaringDay(site, "2026-08-19", {
    models: ["icon_eu", "gfs_seamless"],
    profile: GLIDER_CLUB,
    timeoutMs: 8000,
    retries: 2,
    cache: memoryCache(),
  });
  if (result.ok) {
    result.value.day;       // SoaringDay, already computed
    result.value.failed;    // models that didn't respond: partial failure, not total
  }
  
  // In tests, no network: inject the fetch.
  await fetchSoaringDay(site, "2026-08-19", {
    fetch: async () => new Response(JSON.stringify(fixture), { status: 200 }),
  });
  
  // What each model serves, verified live and not copied from the docs:
  MODEL_CAPABILITIES.icon_eu.hasBoundaryLayerHeight;   // false — ICON doesn't serve it
  MODEL_CAPABILITIES.icon_eu.hasLiftedIndex;           // false — computed from the sounding
  MODEL_CAPABILITIES.icon_eu.pressureLevelsHpa;        // the ones that actually exist
  soundingModels();                                    // models that serve vertical profiles
  void [fetchSoaringDay, memoryCache, MODEL_CAPABILITIES, soundingModels, GLIDER_CLUB, result];
  return undefined;
}
